spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root123
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      #      ddl-auto: create
      ddl-auto: update
  mvc:
    format:
      date-time: iso
  #  main:
  #    allow-bean-definition-overriding: true
  #    allow-circular-references: true
  sql:
    init:
      #      mode: always
      mode: never

  redis:
    host: localhost
    port: 6379


springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /docs

api:
  info:
    title: TalkOn
    description: Online queue
    version: 1.0
    terms-of-service: https://unicorn.pdp.uz
    contact-name: pdp.uz
    contact-email: 000
    contact-url: https://pdp.uz
    license-name: Apache 2.0
    license-url: https://www.apache.org/licenses/LICENSE-2.0.html
server:
  port: 2000



